# Generated by Django 3.2.8 on 2021-10-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('januszex', '0002_alter_rangepostalcode_idrangepostalcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalwarehouse',
            old_name='numer',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='localwarehouse',
            old_name='numer',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='localwarehouse',
            old_name='ulica',
            new_name='street',
        ),
    ]
