# Generated by Django 3.2.8 on 2021-12-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('januszex', '0004_auto_20211027_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalwarehouse',
            name='idGlobalWarehouse',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
