# Generated by Django 3.2.8 on 2021-10-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='przyklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(default='', max_length=70)),
                ('col2', models.CharField(default='', max_length=200)),
                ('col3', models.BooleanField(default=False)),
            ],
        ),
    ]
