# Generated by Django 3.2.8 on 2021-10-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_przyklad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazyn_globalny',
            fields=[
                ('id_magazynu_globalnego', models.IntegerField(primary_key=True, serialize=False)),
                ('miasto', models.CharField(max_length=200)),
                ('ulica', models.CharField(max_length=200)),
                ('numer', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Magazyn_lokalny',
            fields=[
                ('id_magazynu_lokalnego', models.IntegerField(primary_key=True, serialize=False)),
                ('miasto', models.CharField(max_length=200)),
                ('ulica', models.CharField(max_length=200)),
                ('numer', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('id_magazynu_globalnego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.magazyn_globalny')),
            ],
        ),
        migrations.DeleteModel(
            name='przyklad',
        ),
    ]
