# Generated by Django 3.2.8 on 2021-10-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20211014_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
