# Generated by Django 3.2.8 on 2021-10-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_delete_tutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazyn_globalny',
            old_name='miasto',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='magazyn_globalny',
            old_name='id_magazynu_globalnego',
            new_name='id_global_warehouse',
        ),
        migrations.RenameField(
            model_name='magazyn_globalny',
            old_name='kod_pocztowy',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='magazyn_globalny',
            old_name='ulica',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='magazyn_lokalny',
            old_name='miasto',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='magazyn_lokalny',
            old_name='id_magazynu_globalnego',
            new_name='id_global_warehouse',
        ),
        migrations.RenameField(
            model_name='magazyn_lokalny',
            old_name='id_magazynu_lokalnego',
            new_name='id_local_warehouse',
        ),
        migrations.RenameField(
            model_name='magazyn_lokalny',
            old_name='kod_pocztowy',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='magazyn_lokalny',
            old_name='ulica',
            new_name='street',
        ),
    ]
