# Generated by Django 3.2.8 on 2021-10-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20211018_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazyn_globalny',
            new_name='GlobalWarehouse',
        ),
        migrations.RenameModel(
            old_name='Magazyn_lokalny',
            new_name='LocalWarehouse',
        ),
    ]
